const posts = [{id: 1,
            topic: "Tech",
            title: "Generative UI: When AI Becomes Your Design Partner",
            summary :"Discover how AI-powered design tools are revolutionizing creative workflows, enabling designers to iterate faster and explore previously impossible concepts.",
            date:"June 24, 2025",
            readTime:"10 min",
            fullText:"The full text of the article comes in here."},
            {id:2,
            topic: "Tech",
            title: "Generative UI: When AI Becomes Your Design Partner",
            summary :"Discover how AI-powered design tools are revolutionizing creative workflows, enabling designers to iterate faster and explore previously impossible concepts.",
            date:"June 24, 2025",
            readTime:"10 min",
            fullText:"The full text of the article comes in here."},
            {id:3,
            topic: "Tech",
            title: "Generative UI: When AI Becomes Your Design Partner",
            summary :"Discover how AI-powered design tools are revolutionizing creative workflows, enabling designers to iterate faster and explore previously impossible concepts.",
            date:"June 24, 2025",
            readTime:"10 min",
            fullText:"The full text of the article comes in here."},
            {id:4,
            topic: "Tech",
            title: "Generative UI: When AI Becomes Your Design Partner",
            summary :"Discover how AI-powered design tools are revolutionizing creative workflows, enabling designers to iterate faster and explore previously impossible concepts.",
            date:"June 24, 2025",
            readTime:"10 min",
            fullText:"The full text of the article comes in here."},
            {id:5,
            topic: "Tech",
            title: "Generative UI: When AI Becomes Your Design Partner",
            summary :"Discover how AI-powered design tools are revolutionizing creative workflows, enabling designers to iterate faster and explore previously impossible concepts.",
            date:"June 24, 2025",
            readTime:"10 min",
            fullText:"The full text of the article comes in here."},
            {id:6,
            topic: "Tech",
            title: "Generative UI: When AI Becomes Your Design Partner",
            summary :"Discover how AI-powered design tools are revolutionizing creative workflows, enabling designers to iterate faster and explore previously impossible concepts.",
            date:"June 24, 2025",
            readTime:"10 min",
            fullText:"The full text of the article comes in here."},
            {id:7,
            topic: "Tech",
            title: "Generative UI: When AI Becomes Your Design Partner",
            summary :"Discover how AI-powered design tools are revolutionizing creative workflows, enabling designers to iterate faster and explore previously impossible concepts.",
            date:"June 24, 2025",
            readTime:"10 min",
            fullText:"The full text of the article comes in here."}]


            export default posts;